name: Semgrep TXT Report


on: [push, pull_request]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Semgrep
        run: python -m pip install semgrep

      - name: Run Semgrep and save as TXT
        run: |
          semgrep --config=p/owasp-top-ten --json > semgrep-owasp.json

      - name: Upload TXT report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-owasp.json
          retention-days: 7
