name: Semgrep TXT Report


on: [push, pull_request]

jobs:
  semgrep-scan:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Semgrep via action
        uses: returntocorp/semgrep-action@v1
        with:
          config: auto
          output: txt
          options: --timeout=600

      - name: Upload TXT report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-results.txt
          retention-days: 7
